> Projeto Desenvolve <br>
Programação Intermediária com Python <br>
Profa. Camila Laranjeira (mila@projetodesenvolve.com.br) <br>

# 3.6 - Pandas

## Exercícios
Antes de continuar, baixe os arquivos das bases de dados de partidas em Copas do Mundo e salve na mesma pasta deste notebook.
* https://raw.githubusercontent.com/camilalaranjeira/python-intermediario/main/fifa-wc/matches_1930_2022.csv
* https://raw.githubusercontent.com/camilalaranjeira/python-intermediario/main/fifa-wc/matches_1991_2023.csv

A célula a seguir já carrega os dados em CSV e ajusta as colunas para trabalharmos com os nomes traduzidos (como fizemos em aula).

#### Q1.
Faça as conversões de tipo necessárias para que a saída do comando `wc.info()` seja como apresentado a seguir. E **salve o novo dataframe** com o comando `df.to_csv('wc_formatado.csv')`.

```
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype         
---  ------             --------------  -----         
 0   time_1             1312 non-null   string        
 1   time_2             1312 non-null   string        
 2   gols_1             1312 non-null   int64         
 3   gols_2             1312 non-null   int64         
 4   data               1312 non-null   datetime64[ns]
 5   ano                1312 non-null   int64         
 6   país_sede          1312 non-null   string        
 7   comparecimento     1312 non-null   int64         
 8   resultado          1312 non-null   string        
 9   rodada             1312 non-null   category      
 10  gols_1_detalhes    970 non-null    string        
 11  gols_2_detalhes    771 non-null    string        
 12  gols_1_contra      57 non-null     string        
 13  gols_2_contra      30 non-null     string        
 14  gols_1_penalti     170 non-null    string        
 15  gols_2_penalti     119 non-null    string        
 16  cartao_vermelho_1  59 non-null     string        
 17  cartao_vermelho_2  65 non-null     string        
 18  cartao_amarelo_1   834 non-null    string        
 19  cartao_amarelo_2   857 non-null    string        
 20  copa               1312 non-null   string 
```

In [9]:
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 12)

# Carregar os dados
wcwomen_df = pd.read_csv('matches_1991_2023.csv')
wcmen_df   = pd.read_csv('matches_1930_2022.csv')

# Juntar os dados feminino e masculino
wc = pd.concat((wcwomen_df, wcmen_df)).reset_index(drop=True)

# Traduzir os nomes das colunas
nomes_traduzidos = {
    'home_team': 'time_1', 'away_team': 'time_2', 'home_score': 'gols_1', 'away_score': 'gols_2',
    'Date': 'data', 'Year': 'ano', 'Host': 'país_sede', 'Attendance': 'comparecimento',
    'Score': 'resultado', 'Round': 'rodada', 'home_goal': 'gols_1_detalhes', 'away_goal': 'gols_2_detalhes',
    'home_own_goal': 'gols_1_contra', 'away_own_goal': 'gols_2_contra',
    'home_penalty_goal': 'gols_1_penalti', 'away_penalty_goal': 'gols_2_penalti',
    'home_red_card': 'cartao_vermelho_1', 'away_red_card': 'cartao_vermelho_2',
    'home_yellow_card_long': 'cartao_amarelo_1', 'away_yellow_card_long': 'cartao_amarelo_2'
}

wc = wc.loc[:, nomes_traduzidos.keys()]
wc.columns = nomes_traduzidos.values()

# Criar coluna copa (Masculina se ano par, Feminina se ano ímpar)
wc['copa'] = wc['ano'].apply(lambda x: 'Masculina' if x % 2 == 0 else 'Feminina').astype('string')

# Converter tipos de dados
wc['time_1'] = wc['time_1'].astype('string')
wc['time_2'] = wc['time_2'].astype('string')
wc['país_sede'] = wc['país_sede'].astype('string')
wc['resultado'] = wc['resultado'].astype('string')

wc['rodada'] = wc['rodada'].astype('category')

colunas_str = [
    'gols_1_detalhes', 'gols_2_detalhes',
    'gols_1_contra', 'gols_2_contra',
    'gols_1_penalti', 'gols_2_penalti',
    'cartao_vermelho_1', 'cartao_vermelho_2',
    'cartao_amarelo_1', 'cartao_amarelo_2'
]
for col in colunas_str:
    wc[col] = wc[col].astype('string')

wc['data'] = pd.to_datetime(wc['data'])

wc['gols_1'] = wc['gols_1'].astype('int64')
wc['gols_2'] = wc['gols_2'].astype('int64')
wc['ano'] = wc['ano'].astype('int64')
wc['comparecimento'] = wc['comparecimento'].astype('int64')

# Salvar arquivo formatado
wc.to_csv('wc_formatado.csv', index=False)

# Conferir o resultado
wc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1312 entries, 0 to 1311
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   time_1             1312 non-null   string
 1   time_2             1312 non-null   string
 2   gols_1             1312 non-null   int64
 3   gols_2             1312 non-null   int64
 4   data               1312 non-null   datetime64[ns]
 5   ano                1312 non-null   int64
 6   país_sede          1312 non-null   string
 7   comparecimento     1312 non-null   int64
 8   resultado          1312 non-null   string
 9   rodada             1312 non-null   category
 10  gols_1_detalhes    970 non-null    string
 11  gols_2_detalhes    771 non-null    string
 12  gols_1_contra      57 non-null     string
 13  gols_2_contra      30 non-null     string
 14  gols_1_penalti     170 non-null    string
 15  gols_2_penalti     119 non-null    string
 16  cartao_vermelho_1  59 non-null     string
 17  cartao_vermelho_2  65 non-null     string
 18  cartao_amarelo_1   834 non-null    string
 19  cartao_amarelo_2   857 non-null    string
 20  copa               1312 non-null   string
dtypes: category(1), datetime64[ns](1), int64(4), string(15)
memory usage: 206.8 KB

#### Q2.
Apresente a linha do dataframe `wc` que corresponde ao jogo com maior audiência da história.

In [11]:
# Encontrar o maior valor de audiência
maior_audiencia = wc['comparecimento'].max()

# Filtrar a linha correspondente
jogo_mais_assistido = wc[wc['comparecimento'] == maior_audiencia]

# Mostrar o resultado
jogo_mais_assistido

,time_1,time_2,gols_1,gols_2,data,ano,país_sede,comparecimento,resultado,rodada,gols_1_detalhes,gols_2_detalhes,gols_1_contra,gols_2_contra,gols_1_penalti,gols_2_penalti,cartao_vermelho_1,cartao_vermelho_2,cartao_amarelo_1,cartao_amarelo_2,copa
1238,Uruguay,Brazil,2,1,1950-07-16,1950,Brazil,173850,2–1,Final stage,Juan Alberto Schiaffino · 66|Alcides Ghiggia · 79,Friaça · 47,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Masculina

#### Q3.
Aplicando operações sobre as colunas `ano` e `copa` do dataframe `wc`, apresente quantas copas femininas e quantas copas masculinas já aconteceram na história.

Exemplo de saída (valores inventados):
```
Masculina: 22
Feminina: 9
```

In [13]:
# Contar quantas copas masculinas e femininas existem no dataframe (coluna 'copa' e 'ano')
# Como cada copa tem vários jogos, para contar as copas únicas usamos o ano e o tipo da copa

copas_unicas = wc[['ano', 'copa']].drop_duplicates()

contagem = copas_unicas['copa'].value_counts()

print(f"Masculina: {contagem.get('Masculina', 0)}")
print(f"Feminina: {contagem.get('Feminina', 0)}")

Masculina: 22
Feminina: 9

#### Q3. 
Crie um dataframe `participacao` com as colunas `país`, `copa`, e `num_copas` que armazena a quantidade de copas do mundo que cada país participou, informando se é da copa masculina ou feminina. Ao final imprima, como apresentado a seguir, o top 5 países de cada competição que mais participou de copas do mundo.

Exemplo de saída (valores inventados):
```
país            copa        num_copas
Brazil          Feminina    8
Unites States   Feminina    8
Germany         Feminina    8
Japan           Feminina    7
Colombia        Feminina    7
```

```
país            copa        num_copas
Brazil          Masculina   21
Germany         Masculina   21
Argentina       Masculina   20
England         Masculina   20
Mexico          Masculina   20
```

In [15]:
# Selecionar as colunas que indicam país, copa e ano único para evitar duplicados de jogos no mesmo ano
# Os países participantes são os times 1 e 2; precisamos contar participação de ambos

# Criar um dataframe com país, copa e ano, juntando os times 1 e 2
df_time_1 = wc[['time_1', 'copa', 'ano']].rename(columns={'time_1': 'país'})
df_time_2 = wc[['time_2', 'copa', 'ano']].rename(columns={'time_2': 'país'})

# Concatenar para juntar participações dos dois times
df_todos = pd.concat([df_time_1, df_time_2])

# Remover duplicatas (mesmo país, mesma copa, mesmo ano)
df_todos = df_todos.drop_duplicates()

# Contar quantas copas cada país participou, agrupando por país e copa
participacao = df_todos.groupby(['país', 'copa']).size().reset_index(name='num_copas')

# Mostrar top 5 de cada copa
print("Top 5 Feminina:")
print(participacao[participacao['copa']=='Feminina'].sort_values(by='num_copas', ascending=False).head(5))

print("\nTop 5 Masculina:")
print(participacao[participacao['copa']=='Masculina'].sort_values(by='num_copas', ascending=False).head(5))

Top 5 Feminina:
        país      copa  num_copas
78   Nigeria  Feminina          9
110   Sweden  Feminina          9
63     Japan  Feminina          9
81    Norway  Feminina          9
45   Germany  Feminina          9

Top 5 Masculina:
         país       copa  num_copas
11     Brazil  Masculina         22
3   Argentina  Masculina         18
60      Italy  Masculina         18
71     Mexico  Masculina         17
44     France  Masculina         16

#### Q4. 
* Crie um dataframe `gols` com duas colunas `país` e `total_gols` com o total de gols marcados por cada país durante todas as copas do mundo, juntando gols em casa (`gols_1`) e gols como time visitante (`gols_2`).
* Imprima o dataframe `gols` ordenado de forma decrescente, para que os times com mais gols fiquem no topo.

Segue um exemplo ilustrativo com o formato do dataframe resultado:

```
país        total_gols
Brazil      120
Argentina   112
Germany     107
...
```

In [17]:
# Somar gols feitos como time_1
gols_casa = wc.groupby('time_1')['gols_1'].sum().reset_index()
gols_casa.columns = ['país', 'gols_casa']

# Somar gols feitos como time_2
gols_fora = wc.groupby('time_2')['gols_2'].sum().reset_index()
gols_fora.columns = ['país', 'gols_fora']

# Juntar os dois dataframes para somar os gols totais
gols = pd.merge(gols_casa, gols_fora, on='país', how='outer').fillna(0)

# Somar gols casa + fora
gols['total_gols'] = gols['gols_casa'] + gols['gols_fora']

# Selecionar as colunas finais e ordenar decrescente
gols = gols[['país', 'total_gols']].sort_values(by='total_gols', ascending=False).reset_index(drop=True)

# Mostrar resultado
print(gols)

                   país  total_gols
0                Brazil       308.0
1               Germany       254.0
2         United States       182.0
3                France       180.0
4                Sweden       165.0
..                  ...         ...
87              Bolivia         1.0
88    Dutch East Indies         0.0
89              Vietnam         0.0
90                Zaire         0.0
91  Trinidad and Tobago         0.0

[92 rows x 2 columns]

#### Q5. 
Qual país tomou mais cartões amarelos somando todas as copas?

Neste exercício você vai trabalhar com as colunas `cartao_amarelo_1` e `cartao_amarelo_2` onde cada observação é uma string represetando uma lista dos cartões amarelos de um único jogo na forma `minuto|placar|jogador(a)`. Por exemplo:
```
['16’|1:0|Rosana Gómez', '20’|2:0|Gabriela Chávez]
```

Recomendo criar colunas `num_cartoes_1` e `num_cartoes_2` a partir de cada coluna `cartao_amarelo_X` usando o método genérico `apply` para chamar uma função que você vai criar para transformar uma observação de cartão amarelo em uma contagem de elementos da lista. 

Lembre de levar em consideração que muitas observações são `NaN`. 

Em seguida faça sua mágica para agrupar as informações por país, acumular os cartões de jogos em casa e jogos visitante, e produzir o resultado final como apresentado a seguir (valores inventados):

```
país        cartões amarelos
Argentina   97
England     93
Australia   93
...
```

In [19]:
# Função para contar o número de cartões amarelos a partir da string da lista
def contar_cartoes(valor):
    if pd.isna(valor):
        return 0
    try:
        # Remove colchetes e separa os itens da lista
        valor = valor.strip("[]")  # tira os colchetes
        if not valor:
            return 0
        # separa por vírgula, que separa os cartões
        cartoes = valor.split("', '")
        return len(cartoes)
    except:
        return 0

# Criar colunas com a contagem de cartões amarelos em casa e fora
wc['num_cartoes_1'] = wc['cartao_amarelo_1'].apply(contar_cartoes)
wc['num_cartoes_2'] = wc['cartao_amarelo_2'].apply(contar_cartoes)

# Somar cartões por país (como time_1)
cartoes_casa = wc.groupby('time_1')['num_cartoes_1'].sum().reset_index()
cartoes_casa.columns = ['país', 'cartoes']

# Somar cartões por país (como time_2)
cartoes_fora = wc.groupby('time_2')['num_cartoes_2'].sum().reset_index()
cartoes_fora.columns = ['país', 'cartoes']

# Juntar as duas contagens
cartoes_total = pd.concat([cartoes_casa, cartoes_fora])
cartoes_total = cartoes_total.groupby('país')['cartoes'].sum().reset_index()

# Ordenar do maior para o menor
cartoes_total = cartoes_total.sort_values(by='cartoes', ascending=False).reset_index(drop=True)

# Mostrar resultado
print(cartoes_total)

                 país  cartoes
0              Brazil      168
1           Argentina      162
2             Germany      124
3         Netherlands      117
4               Italy      106
..                ...      ...
87            Vietnam        2
88              Zaire        2
89     Chinese Taipei        1
90  Dutch East Indies        0
91               Cuba        0

[92 rows x 2 columns]

#### Q6.
Qual o top10 jogadores com mais gols em copa? Considere gols em jogo e gols de pênalti.

Para conseguir essa informação, você precisará trabalhar com as colunas:
```
10  gols_1_detalhes         
11  gols_2_detalhes    
14  gols_1_penalti     
15  gols_2_penalti     
```

Essas também são colunas textuais, onde cada observações apresenta todos os gols de uma partida separados pelo caracter `|`. Cada gol está na forma `'Jogador(a) · minuto’'`. Por exemplo:
```
'Alex Morgan · 12’|Rose Lavelle · 20’'
```

Lembre de levar em consideração que muitas observações são `NaN`. 

Recomendo criar um dicionário à parte, onde cada chave será um jogador encontrado nessas colunas do dataframe `wc` e o valor correspondente será a contagem de ocorrências desses nomes.

Em seguida basta converter o seu dicionário em um dataframe e imprimí-lo na forma (valores não são inventados 😁):
```
jogador(a)      num_gols 
Marta           17
Miroslav Klose  16
... 
```

In [25]:

from collections import defaultdict

# Função para extrair os nomes dos jogadores de uma string de gols
def extrair_jogadores(gols_str):
    if pd.isna(gols_str) or gols_str.strip() == '':
        return []
    try:
        gols = gols_str.split('|')
        jogadores = [gol.split('·')[0].strip() for gol in gols if '·' in gol]
        return jogadores
    except:
        return []

# Inicializar o dicionário de contagem de gols
contagem_gols = defaultdict(int)

# Listar todas as colunas com informações de gols
colunas_gols = ['gols_1_detalhes', 'gols_2_detalhes', 'gols_1_penalti', 'gols_2_penalti']

# Contar os gols
for col in colunas_gols:
    for linha in wc[col].dropna():
        jogadores = extrair_jogadores(linha)
        for nome in jogadores:
            contagem_gols[nome] += 1

# Converter dicionário para DataFrame
df_goleadores = pd.DataFrame(list(contagem_gols.items()), columns=['jogador(a)', 'num_gols'])

# Ordenar por número de gols em ordem decrescente
df_goleadores = df_goleadores.sort_values(by='num_gols', ascending=False).reset_index(drop=True)

# Mostrar o Top 10
print(df_goleadores.head(10))

         jogador(a)  num_gols
0    Miroslav Klose        16
1           Ronaldo        14
2      Birgit Prinz        14
3     Just Fontaine        13
4       Gerd Müller        13
5              Pelé        12
6      Abby Wambach        12
7     Sándor Kocsis        11
8  Jürgen Klinsmann        11
9           Sun Wen        10